#!/usr/bin/env bash
#!/bin/bash

repoName=${PWD##*/}
userNameOrOrganizationName="USERNAME_OR_ORGANIZATION_NAME"
userName="PUT_GITHUB_USERNAME_HERE"
password="PUT_GITHUB_PASSWORD_OR_TOKEN_HERE"

if ! git config remote.github.url > /dev/null; then
	git remote add github https://${userName}:${password}@github.com/${userNameOrOrganizationName}/${repoName}
fi

while read oldrev newrev ref
do
	if [[ $ref =~ .*/master$ ]];
	then
		echo "Master ref received. Deploying master branch to github ..."
		git push github master -f
	else
		echo "Ref $ref successfully received. Doing nothing."
		
	fi
done
